TOKEN = '1092261236:AAGz-OItiVwTyQbokHP_0BJezxYveI0GQWw'
TIMEZONE = 'Europe/Moscow'
TIMEZONE_COMMON_NAME = 'Moscow'

DBHOST = '127.0.0.1'
DBUSER = 'root'
DBPASSWORD = ''
DBNAME = 'test'
DBCHARSET = 'utf8mb4'
